const mongoose = require("mongoose");

mongoose
  .connect(process.env.DATABASE_URL)
  .then(() => {
    console.log("Quotes Mongo Connected");
  })
  .catch((error) => {
    console.log("ERROR: MongoDB not connected", error);
  });
const QuotesSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  quote: {
    type: [String],
    required: true,
  },
});

const quoteCollection = new mongoose.model("MarcusQuotes", QuotesSchema);

async function checkIfMultiple() {
  const check = await quoteCollection.findOne({ name: "QuotesAccess" });
  if (!check) {
    const quotes = [
      //introduction

      "I am convinced that no man can do a real injury, because no man can force me to misbehave myself ; nor can I find it in my heart to hate or be angry with one of my own nature and family.",
      "The truth is, that the state in which the rulers are most reluctant to govern is best and most quietly governed, and the state in which they are most willing is the worst.",
      "He draws a noble moral from the transitoriness of our being. Not '' Let us eat and drink, for tomorrow we die ,'' is the teachings of the Meditations but rather, '' Let us use this life well, since we have no other.'' The consolation for death must be sought in the consciousness of duty done. If we have lived well, we should be content to die, no matter whether our years be many or few.",

      // Book 1

      "i.4) I have to thank my great-grandfather that I did not go to a public school, but had good masters at home, and learnt to know that one ought to spend liberally on such things.",
      "i.8) Apollonius taught me to give my mind its due freedom, and disengage it from dependence upon chance, and not to regard, though ever so little, anything uncountenanced by reason. To maintain an equality of temper, even in acute pains, and loss of children, or tedious sickness. His practice was an excellent instance, that a man may be forcible and yet unbend his humour as occasion requires. The heaviness and impertinence of his scholars could seldom rouse his ill-temper. As for his learning, and the peculiar happiness of his manner in teaching, he was so far from being proud of himself upon this score, that one might easily perceive, he thought it one of the least things which belonged to him. This great man let me into the true secret of receiving an obligation, without either lessening myself, or seeming ungrateful to my friend.",
      "i.9) The philosopher Sextus recommended good humour to me, and showed me the pattern of a house-hold governed in a fatherly manner. He also bade me make nature and reason my rule to live by. By his precedent I was instructed to appear with an unaffected gravity, to study the temper and circumstances of my friends in order to oblige them. I saw him bearing with the ignorant and undiscerning ,complaisant and obliging to all people, so that his conversation was more charming than flattery ; and yet at the same time he was held in the highest reverenceby others. Conversing with this philosopher helped me to draw up a true, intelligible, and methodical scheme for life and manners, and never so much as to show the least sign of anger, or any other disturbing thought, but to be perfectly calm and indifferent yet tender-hearted. However, he let me see in himself that a man might show his good-will significantly enough, without noise and display, and likewise possess great knowledge without vanity and ostentation.",
      "i.10) Alexander the Grammarian taught me not to be ruggedly critical about words, nor find fault with people for improprieties of phrase or pronunciation,but to set them right by speaking the thing properly myself, and that either by way of answer, assent, orinquiry, or by some such other indirect and suitable correction.",
      "i.11) Fronto taught me that envy, tricking, and dissimulation are the character and consequences of tyranny ; and that those we call patricians have commonly not much fatherly feeling in them.",
      "i.14) I am indebted to Severus for the love I bear to my relations, and towards justice and truth....... —It was of him I learned not to grow wise by starts and sudden fancies, but to be a constant admirer of philosophy and improvement ; that a man ought to be generous and obliging, hope the best of matters, and never question the affection of his friends ; to be free in showing a reasonable dislike of another, and no less clear in hhis own expectations and desires ; and not to put his friends to the trouble of divining what he would be at.",
      "i.15)I learned from Maximus to command myself, and not to be too much drawn towards anything; to be full of spirits under sickness and misfortune ; to appear with modesty, obligingness, and dignity of behaviour ; to turn off business smoothly as it arises, without drudging and complaint. Whatever he did,all men believed him, that as he spoke, so he thought,and whatever he did, that he did with a good intent. He attained that greatness of mind, not to wonder or start at anything ; neither to hurry an enterprise, nor sleep over it; never to be puzzled or dejected, nor to put on an appearance of friendliness ; not to be angry or suspicious, but ever ready to do good, and to forgive and speak truth ; and all this as one who seemed rather of himself to be straight and right, thanever to have been rectified. Nobody ever could fancy they were slighted by him, or dared to think themselves his betters. Besides all this, he had an agreeable wit.",

      // Book 2

      "ii.1) Remember to put yourself in mind every morning, that before night it will be your luck to meet with some busy-body, with some ungrateful, abusive fellow, with some knavish, envious, or unsociable churl or other. Now all this perverseness in them proceeds from their ignorance of good and evil ; and since it has fallen to my share to understand the natural beauty of a good action, and the deformity of an ill one—since I am satisfied the person disobliging is of kin to me, and though we are not just of the same flesh and blood, yet our minds are nearly related, being both extracted from the Deity—I am likewise convinced that no man can do me a real injury, because no man can force me to misbehave myself, nor can I find it in my heart to hate or to be angry with one of my own nature and family.",
      "ii.4) Remember how often you have postponed minding your interest, and let slip those opportunities the gods have given you. It is now high time to consider what sort of world you are part of, and from what kind of governor of it you are descended ; that you have a set period assigned you to act in, and unless you improve it to brighten and compose your thoughts, it will quickly run off with you, and be lost beyond recovery.",
      "ii.5) Take care always to remember that you are a man and a Roman ; and let every action be done with perfect and unaffected gravity, humanity, freedom, and justice. And be sure you entertain no fancies, which may give check to these qualities. This is possible, if you will but perform every action as though it were your last ; if your appetites and passions do not cross upon your reason ; if you keep clear of rashness, and have nothing of insincerity and self-love to infect you, and do not complain of your destiny. You see what a few points a man has to gain in order to attain to a godlike way of living for he that comes thus far, performs all which the immortal powers will require of him.",
      "ii.7) Do not let accidents disturb, or outward objectsengross your thoughts, but keep your mind quiet anddisengaged, that you may be at leisure to learn something good, and cease rambling from one thing toanother. There is likewise another sort of roving tobe avoided ; for some people are busy and yet donothing ; they fatigue and wear themselves out, andyet aim at no goal, nor propose any general end ofaction or design.",
      "ii.8) A man can rarely be unhappy by being ignorant of another's thoughts ; but he that does not attend tothe motions of his own is certainly unhappy.",
      "ii.10) Theophrastus, in comparing the degrees of faults(as men would commonly distinguish them), talks like a philosopher when he affirms that those instances of misbehaviour which proceed from desire are greater than those of which anger is the occasion. For a man that is angry seems to quit his hold of reason unwillingly and with pain, and start out of rule before he is aware. But he that runs riot out of desire,being overcome by pleasure, loses all hold on himself,and all manly restraint. Well, then, and like a philosopher, he said that he of the two is the more to be condemned that sins with pleasure than he that sins with grief. For the first looks like an injured person, and is vexed, and, as it were, forced into a passion ; whereas the other begins with inclination, and commits the fault through desire.",
      "ii.11) Manage all your actions, words, and thoughts accordingly, since you may at any moment quit life. And what great matter is the business of dying ? If the gods are in being, you can suffer nothing, for they will do you no harm. And if they are not, or take no care of us mortals—why, then, a world without either gods or Providence is not worth a man's while to live in. But, in truth, the being of the gods, and their concern in human affairs, is beyond dispute. And they have put it entirely in a man's power not to fall into any calamity properly so-called. And if other misfortunes had been really evils, they would have provided against them too, and furnished man with capacity to avoid them. But how can that which cannot make the man worse make his life so ? I can never be persuaded that the universal Nature neglected these matters through want of knowledge, or, having that, yet lacked the power to prevent or correct the error ; or that Nature should commit such a fault, through want of power or skill, as to suffer things, really good and evil, to happen promiscuously to good and bad men. Now, living and dying, honour and infamy, pleasure and pain, riches and poverty all these things are the common allotment of the virtuous and vicious, because they have nothing intrinsically noble or base in their nature ; and, therefore, to speak properly, are neither good nor bad.",

      // Book 3

      "iii.1)We ought not only to remember that life is wearing off, and a smaller part of it is left daily, but also to consider that if a man's life should happen to be longer than ordinary, yet it is uncertain whether his mind will keep pace with his years, and afford him sense enough for business, and power to contemplate things human and divine. For if the manbegins to dote, it is true the mere animal life goes on he may breathe, and be nourished, and be furnished with imagination and appetite; but to make any proper use of himself, to fill up the measure of his duty, to distinguish appearances, and to know whether it is time for him to walk out of the world or not—as to all such noble functions of reason and judgment, the man is perfectly dead already. It concerns us, therefore, to push forward, and make the most of our matters, for death is continually advancing ; and besides that, our understanding sometimes dies before us.",
      "iii.3)Hippocrates, who cured so many diseases, himself fell ill and died. The Chaldeans, who foretold other people's death, at last met with their own fate. Alexander, Pompey, and Julius Csesar, who had destroyed so many towns, and cut off so many thousands of horse and foot in the field, were forced at last to march off themselves. Heraclitus, who argued so much about the universal conflagration, died through water by a dropsy. Democritus was eaten up with vermin ; another sort of vermin destroyed Socrates. What are these instances for ? Look you : you have embarked, you have made your voyage and your port; debark then without more ado. If you happen to land upon another world, there will be gods enough to take care of you ; but if it be your fortune to drop into nothing, why, then you will be nomore solicited with pleasure and pain. Then you will have done drudging for your outer covering, which is the more unworthy in proportion as that which serves it is worthy ; for the one is all soul, intelligence, anddivinity, whereas the other is but dirt and corruption.",
      "iii.4)For the future, do not spend your thoughts upon other people, unless you are led to it by common interest. For the prying into foreign business—that is, musing upon the talk, fancies, and contrivances of another, and guessing at the what and why of his actions—does but make a man forget himself, and ramble from his own guiding principle. He ought, therefore, not to work his mind to no purpose, nor throw a superfluous link into the chain of thought; and more especially, to avoid curiosity and malice in his inquiry. Accustom yourself, therefore, to think upon nothing but what you could freely reveal, if the question were put to you; so that if your soul were thus laid open, there would be nothing appear but what was sincere, good-natured, and public-spirited—not so much as one voluptuous or luxurious fancy, nothing of hatred, envy, or unreasonable suspicion, nor aught else which you could not bring to the light without blushing. A man thus qualified, who does not delay to assume the first rank among mortals, is a sort of priest and minister of the gods, and makes a right use of the Deity within him. By the assistance thereof, he is preserved, uninfected with pleasure, invulnerable against pain—out of the reach of injury, and above the malice of evil people. Thus he wrestles in the noblest fight, to hold his own against all his passions and, penetrated with the spirit of justice, welcomes with his whole heart all that happens and is allotted to him. He never minds other people's speech, thoughts, or actions, unless public necessity and general good require it. No; he keeps himself to his own business, and contemplates that portion of the whole allotted him by the fates, and endeavours to do the first as it should be, and believes that his lot is good. For every man's fate is suitable, since it is suited to him. He considers that the rational principle is akin in all men, and that general kindness and concern for the whole world is no more than a piece of human nature—that not every one's good opinion is not worth the gaining, but only that of those who seek to live in accordance with Nature. As for others, he knows their way of living, both at home and abroad, by day and by night, and their companions in their evil way of life, and he bears it in mind. And, why, indeed, should he value the commendation of such people, who are not able even to please themselves?",
      "iii.5)Be not unwilling, selfish, unadvised, or passionate in anything you do. Do not affect quaintness and points of wit: neither talk nor meddle more than is necessary. Take care that the divinity within you has a creditable charge to preside over; that you appear in the character of your sex and age. Act like a Roman Emperor that loves his country, and be always in readiness to quit the field at the first summons; and ere you claim your discharge, manage your credit so, that you need neither swear yourself nor want a voucher. Let your air be cheerful; depend not upon external supports, nor beg your tranquillity of another. And, in a word, never throw away your legs, to stand upon crutches.",
      "iii.6)If, in the whole compass of human life, you find anything preferable to justice and truth; to temperance and fortitude; to a mind self-satisfied with its own rational conduct, and entirely resigned to fate—if, I say, you know anything better than this, turn to it with your whole soul, and enjoy it, accounting it the best. But if there is nothing more valuable than the divinity implanted within you, and this is master of its appetites, examines all impressions, and has detached itself from the senses, as Socrates used to say, and shows itself submissive to the government of the gods, and helpful and benevolent to mankind—if all things are trifles compared with this, give way to nothing else. For if you are once inclined to any such thing, it will no longer be in your power to give your undivided preference to what is your own peculiar good, for it is not lawful that anything of another kind or nature, as either popular applause, or power, or riches, or pleasures, should be suffered to contest with what is rationally and politically good. All these things, if but for a while they begin to please, presently prevail, and pervert a man's mind. Let your choice therefore run all one way, and be bold and resolute for that which is best. Now what is profitable is best. If that means profitable to man as he is a rational being, stand to it; but if it means profitable to him as a mere animal, reject it, and keep your judgment without arrogance. Only take care to make inquiry secure.",
      "iii.7)Hold in honour your opinionative faculty, for this alone is able to prevent any opinion from originating in your guiding principle that is contrary to Nature or the proper constitution of a rational creature. Now, a rational constitution enjoins us to do nothing rashly, and to be kindly disposed towards men, and to submit willingly to the gods.",
      "iii.9)Hold in honour your opinionative faculty, for this alone is able to prevent any opinion from originating in your guiding principle that is contrary to Nature or the proper constitution of a rational creature. Now,a rational constitution eojoins us to do nothing rashly, and to be kindly disposed towards men....",
      "iii.10)—remembering withal, that every man's life lies all within the present, which is but a point of time ; for the past is spent, and the future is uncertain. Life moves in a very narrow compass; yes, and men live in a small corner of the world too. And the most lasting fame will stretch but to a sorry extent ; for, alas ! poor transitory mortals who hand it down know little even of themselves, much less of those who died long before their time.",
      "iii.12)If you will be governed by reason, and manage what lies before you with industry, vigour, and temper; if you will not run out after new distraction, but keep your divinity pure, even as though you must at once render it up again, your mind staunch and well disciplined, as if this trial of behaviour were your last; and, if you will but cleave to this, and be true to the best of yourself, fearing and desiring nothing, but living up to your nature, standing boldly by the truth of your word, and satisfied therewith, then you will be a happy man. But the whole world cannot hinder you from so doing.",

      //Book 4

      "iv.2)Let every action tend to some point, and be perfect in its kind.",
      "iv.4)One's own mind is a place the most free from crowd and noise in the world, if a man's thoughts are such as to ensure him perfect tranquillity within, and this tranquillity consists in the good ordering of the mind. Your way is, therefore, to make frequent use of this retirement, and refresh your virtue in it. And to this end, be always provided with a few short, uncontested notions, to keep your understanding true, and send you back content with the business to which you return.",
      "iv.7)Do not suppose you are hurt, and your complaint ceases. Cease your complaint, and you are not hurt.",
      "iv.8)That which does not make a man worse, does not make his life worse ; and by consequence he has no harm either within or without.",
      "iv.11)If a man affronts you, do not accept his opinion or think just as he would have you do. No, look upon things as reality presents them.",
      "iv.13)Have you any sense in your head? Yes. Why do you not make use of it then ? For if this faculty does bat do its part, I cannot see what more you need wish for.",
      "iv.16)Do but return to the principles of wisdom, and those who take you now for a monkey or a wild beast, will make a god of you in a week's time.",
      "iv.17)Do not act as if you had ten thousand years to throw away. Death stands at your elbow. Be good for something, while you live and it is in your power.",
      "iv.18)What a great deal of time and ease that man gains who lets his neighbor's words, thoughts, and behavior alone, confines his inspections to himself, and takes care that his own actions are honest and righteous. 'Truly,' as Agathon observes, 'we should not wander thus, but run straight to the goal without rambling and impertinence.' ",
      "iv.19)He that is so very solicitous about being talked of when he is dead, and makes his memory his inclination, does not consider that all who knew him will quickly be gone. That his fame will grow less in the next generation, and flag upon the course; and handed from one to another by men who eagerly desire it themselves, and are quenched themselves, it will be quenched at last; but granting your memory and your men immortal, what is their panegyric to you? I do not say, when you are dead, but if you were living, what would commendation signify, unless for some reason of utility? To conclude; if you depend thus servilely upon the good word of other people, you will be unworthy of your nature.",
      "iv.22)Do not run riot ; keep your intentions honest , and your convictions sure.",
      "iv.31)Be satisfied with your business, and learn to love what you were bred to; and as to the remainder of your life, be entirely resigned, and let the gods do their pleasure with your body and your soul. And when this is done, be neither slave nor tyrant to anybody.",
      "iv.33)Those words which were formerly current are now become obsolete. Alas! this is not all; fame tarnishes in time too, and men grow out of fashion as well as language. All these things are transitory, and quickly become as a tale that is told, and are swallowed up in oblivion. I speak this of those who have been the wonder of their age and who shone with unusual lustre. But as for the rest, they are no sooner dead than forgotten. And after all, what does fame everlasting mean? Mere vanity. What then is it that is worth one's while to be concerned for? Why, nothing but this: to bear an honest mind, to act for the good of society, to deceive nobody, to welcome everything that happens as necessary and familiar, and flowing from a like source.",
      "iv.35)He that does a memorable action, and those that report it, are all but short-lived things.",
      "iv.36)Accustom yourself to consider that whatever is produced is produced by alteration; that nature loves nothing so much as changing existing things, and producing new ones like them. For that which exists at present is, as it were, the seed of what shall spring from it. But if you take seed in the common notion, and confine it to the field or the womb, you have a dull fancy.",
      "iv.38)To understand the true quality of people, you must look into their minds, and examine their pursuits and aversions.",
      "iv.43)Time is like a rapid river, and a rushing torrent of all that comes and passes. A thing is no sooner well come, but it is past; and then another is borne after it, and this too will be carried away.",
      "iv.48).....In short, mankind are poor transitory things ! They are one day in the rudiments of life, and almost the next turned to mummy or ashes. Your way is therefore to manage this minute in harmony with nature, and part with it cheerfully ; and like a ripe olive when you drop, be sure to speak well of the mother that bare you, and make your acknowledgments to the tree that produced you.",
      "iv.49)Stand firm like a rock, against which, though the waves batter, yet it stands unmoved, and they fall to rest at last. How unfortunate has this accident made me, cries such an one! Not at all! He should rather say, 'What a happy mortal am I for being unconcerned upon this occasion!' for being neither crushed by the present, nor afraid of what is to come. The thing might have happened to any other man as well as myself; but for all that, everybody would not have been so easy under it.",
      "iv.50)To consider those old people that resigned life so unwillingly, is a common yet not unserviceable aid in facing death. For what are these long-lived mortals more than those that went off in their infancy? What has become of Cadicianus, Fabius, Julianus, and Lepidus, and others like them? They buried a great many, but came at last to it themselves. Upon the whole, the difference between long and short life is insignificant, especially if you consider the accidents, the company, and the body you must go through with. Therefore do not let a thought of this kind affect you. Do but look upon the astonishing notion of time and eternity; what an immense deal has run out already, and how infinite it is still in the future.",

      //Book 5

      "v.1)When you find an unwillingness to rise early in the morning, make this short speech to yourself: I am getting up now to do the business of a man; and am I out of humour for something about that I was made for, and for the sake of which I was sent into the world? Was I then designed for nothing but to doze and keep warm beneath the counterpane? Well! but this is a comfortable way of living. Granting that; were you born only for pleasure? were you never to do anything? Is not action the end of your being? Pray look upon the plants and birds, the ants, spiders, and bees, and you will see them all exerting their nature, and busy in their station.",
      "v.3)Do not think any word or action beneath you which is in accordance with nature; and never be misled by the apprehension of censure or reproach. Where honesty prompts you to say or do anything, never hold it beneath you. Other people have their own guiding principles and impulses; mind them not. Go on in the straight road, pursue your own and the common interest. For to speak strictly, these two are approached by one and the same road.",
      "v.6)Some men, when they do you a kindness, at once demand the payment of gratitude from you; others are more modest than this. However, they remember the favour, and look upon you in a manner as their debtor. A third sort shall scarce know what they have done. These are much like a vine, which is satisfied by being fruitful in its kind, and bears a bunch of grapes without expecting any thanks for it. A fleet horse or greyhound does not make a noise when they have done well, nor a bee neither when she has made a little honey. And thus a man that has done a kindness never proclaims it, but does another as soon as he can, just like a vine that bears again the next season. Now we should imitate those who are so obliging, as hardly to reflect on their beneficence. But you will say, a man ought not to act without reflection. It is surely natural for one that is generous to be conscious of his generosity; yes, truly, and to desire the person obliged should be sensible of it too. What you say is in a great measure true. But if you mistake my meaning, you will become one of those untoward benefactors I first mentioned; indeed, they too are misled by the plausibility of their reasoning. But if you will view the matter in its true colors, never fear that you will neglect any social act.",
      "v.17)To expect an impossibility is madness. Now it is impossible for ill men not to do.",
      "v.23)Reflect frequently upon the instability of things, and how very fast the scenes of nature are shifted. Matter is in a perpetual flux. Change is always and everywhere at work; it strikes through causes and effects, and leaves nothing fixed and permanent. And then how very near us stand the two vast gulfs of time, the past and the future, in which all things disappear. Now is not that man a blockhead that lets these momentary things make him proud, or uneasy, or sorrowful, as though they could trouble him for long?",
      "v.24)Remember what an atom your person is in respect of the universe, what a minute of immeasurable time falls to your share, and what a small concern you are in the empire of fate!",
      "v.25)A man misbehaves himself towards me; what is that to me? The action is his, and the disposition that led him to it is his, and therefore let him look to it. As for me, I am in the condition the universal nature assigns me, and am doing what my own nature assigns me.",
      "v.26)Whether the motions of your body are rugged or agreeable, do not let your ruling and governing principle be concerned with them; confine the impressions to their respective quarters, and let your mind keep her distance, and not mingle with them.",
      "v.34)You may be always successful if you do but set out well, and let your thoughts and practice proceed upon the right method. There are two properties and privileges common to the soul of God and man and all rational beings. The one is, not to be hindered by anything external; the other, to make virtuous intention and action their supreme satisfaction, and not so much as to desire anything farther.",

      //Book 6

      "vi.4)The present appearance of things will quickly undergo a change, and be either exhaled into commonmatter or dispersed.",
      "vi.6)The best way of revenge is not to imitate the injury.",
      "vi.19)Because you find a thing very difficult, do not at once conclude that no man can master it. But whatever you observe proper and practicable by another, believe likewise within your own power.",
      "vi.20)If an antagonist in the circus tears our flesh with his nails, or tilts against us with his head, and wounds us, we do not cry out foul play, nor are we offended at the rough usage, nor suspect him afterwards as a dangerous person in conversation. It is true, when we are at the exercise we guard and parry, but all this is done without raising ill blood, or looking upon the man as an enemy. Let us act in this way in the other instances of life. When we receive a blow, let us disregard it, thinking we are but at a trial of skill, for, as I said before, it is in our power to retire without feeling malice and ill-will.",
      "vi.21)If anyone can convince me of an error, I shall be very glad to change my opinion, for truth is my business, and nobody was ever yet hurt by it. No; he that continues in ignorance and mistake, it is he that receives the mischief.",
      "vi.22)I do my duty, that is enough. As for other things, I shall never be disturbed about them. For they are either without life or without reason, or they have lost their way and cannot find it.",
      "vi.26)Suppose you were asked to spell Antoninus's name, would you sound every letter with emphasis in the company's ears? Or would you return their passion if they were angry? I conceive you would rather go mildly to work, and give them the letters and syllables as they stand, without noise. Apply this to greater instances, and remember that all duties in morality have a determinate number of parts to render them complete. These must be observed, and performed in order; but it must be done smoothly, without growing provoked upon meeting with provocation.",
      "vi.29)It would be a shame if your mind should falter and give in before your body.",
      "vi.31)Rouse and recollect yourself, and you will perceive your trouble lay only in a scene of imagination. And when you are well awake, look upon these realities as you did upon those visions.",
      "vi.38)The mutual dependence all things have, and the relation they stand in to each other, is worth your frequent observation. For all the parts of matter are in some measure linked together and interwoven, and for this reason have a natural sympathy for each other. For one thing comes in order after another, and this comes about through their active movement and harmony, and the unity of their substance.",
      "vi.39)Bring your will to your fate, and suit your mind to your circumstances, and love those people heartily that it is your fortune to be engaged with.",
      "vi.40)If you suppose anything which lies out of your command to be good or evil, your missing the one or falling into the other will unavoidably make you a malcontent against the gods, and cause you to hate those people whom you either know or suspect to be instrumental in your misfortune. To be plain, our being concerned for these objects often makes us very unreasonable and unjust. But if we confine the notion of good and evil to things in our power, then all the motives to complaint will drop off; then we shall neither remonstrate against Heaven, nor quarrel with any mortal living.",
      "vi.54)That which is not for the interest of the whole swarm is not for the interest of a single bee.",

      //Book 7

      "vii.2)Opinions, whether right or wrong, can never be pulled out of your head unless the impressions on which they rest are first removed. It is in your power to kindle them afresh, or to form a right judgment upon the present emergency. And why, then, should I be disturbed at it? For nothing that does not enter my mind, and get within me, can hurt me. Hold to this, and you are safe. Come, I will tell you a way how you may live your time over again. Do but recollect and review what you have seen already, and the work is done.",
      "vii.5)Is my intellect sufficient for this business or not? If it is, I will make use of my talent as given me by heaven for that purpose. If not, I will either let it alone, and resign it to a better capacity, unless that be contrary to my duty, or else I will do what I can. I will give my advice, and put the executing part into an abler hand, and thus the right moment and the general interest may be secured. For whatsoever I act, either by myself, or in conjunction with another, I am always to aim at the advantage of the community.",
      "vii.12)Either stand upright upon your own legs, or upon your crutches.",
      "vii.15)Let people's tongues and actions be what they will, my business is to be good. And make the same speech to myself, that a piece of gold, or an emerald, or purple should. Let people talk and act as they please; I must be an emerald, and I must keep my colour.",
      "vii.18)Is anyone afraid of change? I would gladly know what can be done without it? and what is dearer and more suitable to the universal nature? Pray, must not your wood be transformed before your bath can be ready for you? Must not your meat be changed to make it fit to nourish you? Indeed, what part of life or convenience can go forward without alteration? Now, in all likelihood a change in your condition may be as serviceable to the world in general, as those alterations above mentioned are to you.",
      "vii.21)It will not be long before you will have forgotten all the world, and in a little time all the world will forget you too.",
      "vii.25)That being which governs nature will quickly change the present face of it. One thing will be made out of another by frequent revolutions. And thus the world will be always new.",
      "vii.29)Rub out the colours of imagination. Do not suffer your passions to make a puppet of you. Confine your care to the present. Look through that which happens either to yourself or another. Distinguish the parts of your subject, and divide them into the causal and material element. Think upon your last hour, and do not trouble yourself about other people's faults, but leave them with those that must answer for them.",
      "vii.36)It is a royal thing to be ill spoken of for good deeds.",
      "vii.49)By looking back into history, and considering the fate and revolutions of government, you will be able to draw a guess, and almost prophesy upon the future; for they will certainly be of the same nature, and cannot but be cast in the same mould. So that forty years of human life may serve for a sample of ten thousand. For what more will you see?",
      "vii.58)When any accident happens, call to mind those who have formerly been under the same circumstances, how full of surprise, complaint, and trouble they were about the matter. And where are they now? They are gone, their murmuring could not make them immortal. To what purpose should you imitate their behaviour? Cannot you leave these foreign emotions to those who cause them, and those who are moved by them?",
      "vii.65)Do not return the temper of ill-natured people upon themselves, nor treat them as they do the rest of mankind.",
      "vii.69)He that is come to the top of wisdom and practice, spends every day as if it were his last, and is never guilty of over-excitement, sluggishness, or insincerity.",
      "vii.72)Whatever business tends neither to the improvement of your reason, nor the benefit of society, the rational and social faculty thinks beneath it.",
      "vii.73)When you have done a kindness, and your neighbor is the better for it, why need you be so foolish as to look any farther, and gape for reputation and requital?",

      //Book 8

      "viii.15)Would it not be an odd instance of surprise to stare at a fig-tree for bearing figs? Why then should it seem strange to us for the world to act like itself, and produce things pursuant to quality and kind? This is just as foolish as it would be for a physician to wonder at a fever, or a master of a vessel at a cross blast of wind.",
      "viii.16)To retract or mend a fault at the admonition of a friend in no way hurts your liberty, for it is still your own activity which by means of your own impulse and judgment, and by your own mind, makes you see your mistake.",
      "viii.27)Every man has three relations to acquit himself in: his body that encompasses him makes one, the Divine cause that gives to all men all things another, and his neighbours a third.",
      "viii.33)As to the case of good fortune, take it without pride, and resign it without reluctance.",
      "viii.36)Do not take your whole life into your head at a time, nor burden yourself with the weight of the future, nor form an image of all probable misfortunes. This method will but confound you.",
      "viii.36)Besides, you are to remember, that neither what is past nor what is to come need afflict you, for you have only to deal with the present. Now, this is strangely lessened, if you take it singly and by itself.",
      "viii.44)Make the best of your time while you have it. Those who are so solicitous about fame never consider that future generations will be much the same as the present whom they are vexed with, and they, too, are mortal, what then can the noise or opinions of such little mortals signify to you?",
      "viii.46)No accident can happen to any man but what is consequent to his nature. And the same thing maybe affirmed of a beast, a vine, or a stone. Now if things fare no otherwise than according to kind and constitution, why should you complain? --You may be assured the universal nature has never laid upon you an intolerable evil.",
      "viii.47)If anything external vexes you, take notice that it is not the thing which disturbs you, but your notion about it, which notion you may dismiss at once if you please.",
      "viii.48)The mind is invincible when she turns to herself, and relies upon her own courage; in this case there is no forcing her will, though she has nothing but obstinacy for her defence.",
      "viii.60)Understanding does not always drive onward like an arrow. The mind sometimes by making a halt, and going round for advice, moves straight on none the less, and hits the mark.",

      //Book 9

      "ix.31)Keep a calm spirit towards things that proceed from an external cause, and a just spirit towards those that proceed from a cause within you; that is, let your impulse and action aim at the interest of mankind, for then you know your faculties are in the right posture that nature has set them.",

      //Book 10

      "x.3)Whatever happens, either you have strength to bear it, or you have not. If you have, exert your nature, and never murmur at the matter. But if the weight is too heavy for you, do not complain; it will crush you, and then destroy itself.",
      "x.12)Why need you be anxious about the event when you may examine the enterprise, and debate the reasonableness of it? If you find it practicable, go on contented, and let nothing divert you. But if you cannot see your way, make a halt, and take the best advice upon the case.",
      "x.16)Spend no more time in stating the qualifications of a man of virtue, but endeavour to get them.",

      //Book 11

      "xi.1)The properties of a rational soul are these. She has the privilege to look into her own nature, to cut out her qualities and form herself to what character she pleases. Her business is never spoilt by interruption, as it happens in a dance or a play.",
      "xi.9)People's malice or impertinence cannot beat you off your reason, or stop your progress in virtue. Be not then disconcerted, nor check your good nature towards them. If you meet with opposition and ill-will, you must neither be diverted nor disturbed, but keep your right judgment and action and your temper too towards people who try to hinder you or otherwise annoy you. For as it is a weakness to give in from fear and be diverted from your conduct, so it is likewise to be angry with impertinent people.",
      "xi.12)The figure of the soul is then round and uniform, when she neither reaches after anything foreign, nor shrinks into herself, nor is dispersed or sunk in, but shines in the light by which she surveys the truth of all things and of herself too.",
      "xi.14)People generally despise where they Hatter, and cringe to those they would gladly overtop.",
      "xi.15)How fulsome and hollow does that man look that cries, `I'm resolved to deal straightforwardly with you.` Hark you, friend, what need of all this flourish? Let your actions speak; your face ought to vouch for your speech. I would have virtue look out of the eye, no less apparently than love does in the sight of the beloved. I would have honesty and sincerity so incorporated with the constitution, that it should be discoverable by the senses, and as easily distinguished as a strong breath, so that a man must be forced to find it out whether he would or no.",
      "xi.15)Nothing is more scandalous than false friendship, and, therefore, of all things avoid it. In short, a man of integrity, sincerity, and good-nature can never be concealed, for his character is wrought into his countenance.",
      "xi.18)Do not forget you are like the rest of the world, and faulty yourself in a great many instances: that though you may forbear from some errors, it is not for want of inclination, and that nothing but cowardice, vanity, or some such base principle hinders you from sinning.",
      "xi.18)It is sometimes a hard matter to be certain whether men do wrong, for their actions often are done with a reference to circumstances; and one must be thoroughly informed of a great many things before he can be rightly qualified to give judgment in the case.",
      "xi.29)People do not pretend to teach others to write and read till they have been taught themselves; this rule holds much more of life.",
      "xi.33)He is a madman that expects figs on the trees in winter; and he is little better that calls for his children again when they are dead and buried.",
      "xi.35)Grapes are first sour, then ripe, then raisins, these are all no more than bare alterations; not into nothing, but into something which does not appear at present.",

      //Book 12

      "xii.1)All those things you drudge, and range so much ground for, you may have at your ease, unless you are afraid of making yourself too happy. Your method to do your business is not to concern yourself about the time past, for that is never to be recovered; to rest the future with Providence, and only stick to the present, and improve that to all the noble purposes of piety and justice.",
      "xii.4)I have often wondered how it comes to pass that everybody should love themselves best, and yet value their neighbour's opinion about themselves more than their own.",
      "xii.8)Let it be your method to contemplate spirits apart from the shell they are shut up in, mind the aim of people's actions, examine the value of fame, the force of pain and pleasure, and see what death amounts to, and what reputation, consider upon what account a man grows troublesome to himself, that nobody can be hindered by another, and that everything is opinion.",
      "xii.10)Be not satisfied with a superficial view of things, but penetrate into their matter and form, and the end they were made for.",
      "xii.15)A lamp till it is extinguished holds its light, and shines without interruption, and can you find in your heart to see your truth, honesty, and sobriety extinguished before you?",
      "xii.19)Consider, for it is high time, that you have something more divine in you than the mechanism of passion, than the wires of a puppet. What is there now in my soul? Is it fear, or suspicion, or desire? Or anything of this coarse nature?",
      "xii.20)Take care never to do anything without thought, and design, nor for any other end but what may be serviceable to the interest of society.",
      "xii.22)Remember that all things are opinion, and that it is in your own power to think as you please. Therefore remove the opinion, and then as if you had doubled some dangerous cape, you will have nothing but a steady course, a smooth sea, and a waveless bay to receive you.",
      "xii.32)What a small part of immeasurable and infinite time falls to the share of a single mortal, and how soon is every one swallowed up in eternity. What a handful of the universal matter goes to the making of a human body, and what a very little of the universal soul too!",
      "xii.33)The great business of a man is to improve his mind, therefore consider how he does this. As for all other things, whether in our power to compass or not, they are no better than lifeless ashes and smoke.",

      //END
    ];
    const data = {
      name: "QuotesAccess",
      quote: quotes,
    };

    quoteCollection
      .insertMany(data)
      .then((result) => {
        console.log("Quotes inserted into the database successfully");
      })
      .catch((err) => {
        console.log("some error occurred in creating model");
        console.log(err);
      });
  }
}

checkIfMultiple();
// Replace this array with your actual quotes

module.exports = { quoteCollection }; // Move the export statement here
